config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :teams, only: %i[index show] do
    get 'players', on: :member, to: 'teams#players'
    get 'games', on: :member, to: 'teams#games'
  end

  resources :games, only: %i[index show]

  resources :players, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id           :bigint           not null, primary key
#  home_team_id :bigint           not null
#  away_team_id :bigint           not null
#  uuid         :string           not null
#  status       :string
#  scheduled    :datetime
#  home_points  :integer
#  away_points  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Game < ApplicationRecord
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id               :bigint           not null, primary key
#  nhl_id           :string
#  status           :string
#  full_name        :string
#  first_name       :string
#  last_name        :string
#  abbr_name        :string
#  height           :integer
#  weight           :integer
#  handedness       :string
#  position         :string
#  primary_position :string
#  jersey_number    :integer
#  college          :string
#  experience       :integer
#  birth_place      :string
#  birthdate        :date
#  rookie_year      :integer
#  draft_team_id    :string
#  draft_year       :integer
#  draft_round      :integer
#  draft_pick       :integer
#  team_id          :bigint           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :bigint           not null, primary key
#  nhl_id     :string
#  name       :string
#  market     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Team < ApplicationRecord
  has_many :players
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game
            .includes(:home_team, :away_team)
            .where(scheduled: (1.year + 4.months).ago.all_day)
            .order(scheduled: :asc)
            .each_with_object({}) do |game, hash|
              stats = generate_random_stats
              hash[game.id] = {
                home: {
                  team: game.home_team,
                  stats: stats[:home]
                },
                away: {
                  team: game.away_team,
                  stats: stats[:away]
                },
                totals: random_totals,
                scheduled: game.scheduled
              }
            end
  end

  def show
    @game = Game.find(params[:id])
  end

  private

  def generate_random_stats
    puckline = random_puckline
    home_moneyline = random_moneyline
    away_moneyline = random_moneyline

    if (home_moneyline > 0 && away_moneyline > 0) || (home_moneyline < 0 && away_moneyline < 0)
      if [true, false].sample
        home_moneyline = -home_moneyline
      else
        away_moneyline = -away_moneyline
      end
    end

    {
      home: {
        moneyline: format_number(home_moneyline),
        puckline: format_number(puckline)
      },
      away: {
        moneyline: format_number(away_moneyline),
        puckline: format_number(-puckline)
      }
    }
  end

  def random_moneyline
    rand(101..300) * [-1, 1].sample
  end

  def random_puckline
    rand(-1.5..1.5).round(1)
  end

  def random_totals
    total = rand(5.5..7.5).round(1)
    {
      over: format_number(total),
      under: format_number(-total)
    }
  end

  def format_number(num)
    num.positive? ? "+#{num}" : num.to_s
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def players
    @team = Team.find(params[:id])
    @players = @team.players
  end

  def games
    @team = Team.find(params[:id])
    @games = Game.where("home_team_id = ? OR away_team_id = ?", @team.id, @team.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<div class="table">
  <div class="header">
    <div class="cell"></div>
    <div class="cell">Moneyline</div>
    <div class="cell">Puck line</div>
    <div class="cell">Total</div>
  </div>
  <% @games.each do |id, data| %>
    <% away = data[:away] %>
    <% home = data[:home] %>
    <div class="row-group">
      <div class="row">
        <div class="cell">
          <img src="<%= away[:team].logo %>" />
          <a href="<%= players_team_path(away[:team]) %>" target="_blank">
            <%= "#{away[:team].market} #{away[:team].name}" %>
          </a>
          <span class="at">@</span>
        </div>
        <div class="cell">
          <%= away[:stats][:moneyline] %>
        </div>
        <div class="cell">
          <button>
            <%= away[:stats][:puckline] %>
          </button>
        </div>
        <div class="cell">
          <button> O <%= data[:totals][:over] %> </button>
        </div>
      </div>
      <div class="row">
        <div class="cell">
          <img src="<%= home[:team].logo %>" />
          <a href="<%= players_team_path(home[:team]) %>" target="_blank">
            <%= "#{home[:team].market} #{home[:team].name}" %>
          </a>
        </div>
        <div class="cell">
          <button>
            <%= home[:stats][:moneyline] %>
          </butt>
        </div>
        <div class="cell">
          <button>
            <%= home[:stats][:puckline] %>
          </button>
        </div>
        <div class="cell">
          <button> U <%= data[:totals][:under] %> </button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waffleboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render(ThemeToggleComponent.new) %>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h1>Players</h1>

<% @players.each do |player| %>
  <pre><%= JSON.pretty_generate(JSON.parse(player.to_json)) %></pre>
<% end %>